### ISSUE TITLE
你们这文档是我见过推送中写的最烂的

### ISSUE THREAD

**Issue by aiven163** [MEIZUPUSH/JavaSdk#20]
一脸懵逼，给我一个下载SDK链接，文档中全是说用远程仓库集成的。也没有一个Demo。而且集成了其他几家，倒是说一下如果不需要那些如何拆分啊

**Comment by JasperXgwang** [comment]
没明白你说的没有demo是什么demo，https://github.com/MEIZUPUSH/JavaSdk/blob/master/README.md  这里的文档写的很清楚呀，也包括调用示例，也包括代码中的单元测试，很完善
